### ISSUE TITLE
Is there any way to use project-defined babel plugins?

### ISSUE THREAD

**Issue by kuu** [vinsonchuong/dist-es6#7]
It would be nice if the project could configure the transpilations via .babelrc.

**Comment by vinsonchuong** [comment]
That's a good idea. I'll figure out a way to make that happen!

**Comment by vinsonchuong** [comment]
@kuu, I've built a working example that uses `babel-preset-react` via `.babelrc` here: [vinsonchuong/test-dist-es6-7](https://github.com/vinsonchuong/test-dist-es6-7), and the current version seems already use `.babelrc`. I still had to specify a `devDependency` on `babel-preset-react` in my `package.json` though.

Let me know if this is working for you or if there's a specific usecase that I'm not accounting for.

**Comment by kuu** [comment]
@vinsonchuong You're right... `dist-es6` does refer to the project's .babelrc. That was my home-made babel-plugin's fault. I apologize. m(_ _)m

**Comment by kuu** [comment]
FYI, the issue was actually because I didn't clear ~/.babel.json after updating my self-made babel plugin.
I didn't know that bebel-register stores its compilation results there... 😢 
But thanks and sorry anyway!
